backend:
  name: git-gateway
  branch: main
publish_mode: editorial_workflow
media_folder: static/img

collections:
  - name: blog
    label: Blog
    folder: content
    create: true
    slug: "{{month}}-{{day}}-{{year}}-{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}
